/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.GUI.Panels.NhapKho;

import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.example.BUS.ChiTietPhieuNhapBUS;
import org.example.GUI.Constants.AppConstants;
import org.example.BUS.PhieuNhapBUS;
import org.example.DTO.ChiTietPhieuNhapDTO;
import org.example.DTO.PhieuNhapDTO;
import org.example.GUI.Panels.NhapKho.ChiTietPhieuNhap;
import org.example.GUI.Panels.NhapKho.NhapHang;

/**
 *
 * @author MTeumb
 */
public class NhapKhoPanel extends javax.swing.JPanel {

    private PhieuNhapBUS pnBUS = new PhieuNhapBUS();
    private ChiTietPhieuNhapBUS ctpnBUS;

    /**
     * Creates new form NhapKhoPanel
     */
    public NhapKhoPanel() {
        initComponents();
        loadPhieuNhap();
        ctpnBUS = new ChiTietPhieuNhapBUS();
    }

    public void loadPhieuNhap() {
        List<PhieuNhapDTO> listpn = pnBUS.layTatCaPhieuNhap();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (PhieuNhapDTO phieunhap : listpn) {
            Object[] row = new Object[]{
                phieunhap.getMaPhieuNhap(),
                phieunhap.getHoTenNguoiDung(),
                phieunhap.getTenNhaCungCap(),
                phieunhap.getThoiGianLap(),
                phieunhap.getTrangThai() == 1 ? "Đã Thanh Toán" : "Chưa thanh toán",};
            model.addRow(row);
        }

        jTable1.setModel(model);
    }
    
     public void hienThiChiTietPhieuNhap(JTable table, int id) {
        List<ChiTietPhieuNhapDTO> listct = ctpnBUS.layChiTietPhieuNhap(id);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        for (ChiTietPhieuNhapDTO ctpn : listct) {
            Object[] row = new Object[]{
                ctpn.getTenSanPham(),
                ctpn.getDonGia(),
                ctpn.getSoLuong(),
                ctpn.getDonGia() * ctpn.getSoLuong(),};
            model.addRow(row);
        }
        table.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.getTableHeader().setReorderingAllowed(false);
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        jLabel1.setFont(AppConstants.HEADER_FONT);
        jLabel1.setText("Nhập Hàng");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Nhập", "Tên Người Dùng", "Tên Nhà Cung Cấp", "Thời Gian Lập", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setFont(AppConstants.NORMAL_FONT);
        jButton1.setText("Nhập");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 703, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow == -1) {
                return;
            }

            int id = (int) jTable1.getValueAt(selectedRow, 0);
            ChiTietPhieuNhap dialog = new ChiTietPhieuNhap(null, true);
            hienThiChiTietPhieuNhap(dialog.getTable(), id);

            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        NhapHang NhapHangDiag = new NhapHang(null, true);
        NhapHangDiag.setVisible(true);
        
        loadPhieuNhap();
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
