/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.GUI.Panels.SanPham;

import org.example.BUS.SanPhamBUS;
import org.example.GUI.Constants.AppConstants;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import org.example.DTO.SanPham;

/**
 *
 * @author dtoan
 */
public class SanPhamPanel extends javax.swing.JPanel {

    private SanPhamBUS sanPhamBUS;

    /**
     * Creates new form SanPhamPanel
     */
    public SanPhamPanel() {
        initComponents();
        sanPhamBUS = new SanPhamBUS();
        hienThiDanhSachSanPham(); // Gọi hàm để hiển thị danh sách khi form khởi tạo
    }

    private void hienThiDanhSachSanPham() {
        sanPhamBUS.hienThiSanPhamLenTable(Tb_SanPham); // Gán dữ liệu vào Tb_SanPham
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SanPham_pop_editdel = new javax.swing.JPopupMenu();
        SanPham_pop_Sua = new javax.swing.JMenuItem();
        SanPham_pop_Xoa = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tb_SanPham = new javax.swing.JTable();
        SanPham_btn_Tim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SanPham_txt_Tim = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        SanPham_btn_TaiLai = new javax.swing.JButton();
        SanPham_btn_Them = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tb_SanPham1 = new javax.swing.JTable();

        SanPham_pop_Sua.setText("Sửa");
        SanPham_pop_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanPham_pop_SuaActionPerformed(evt);
            }
        });
        SanPham_pop_editdel.add(SanPham_pop_Sua);

        SanPham_pop_Xoa.setText("Xóa");
        SanPham_pop_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanPham_pop_XoaActionPerformed(evt);
            }
        });
        SanPham_pop_editdel.add(SanPham_pop_Xoa);

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        Tb_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Loại sản phẩm", "Ảnh sản phẩm URL", "Tên sản phẩm", "Nhà sản xuất", "Trạng thái", "Số lượng", "Giá vốn", "Giá lời"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb_SanPham.setCellSelectionEnabled(true);
        Tb_SanPham.setComponentPopupMenu(SanPham_pop_editdel);
        jScrollPane2.setViewportView(Tb_SanPham);
        if (Tb_SanPham.getColumnModel().getColumnCount() > 0) {
            Tb_SanPham.getColumnModel().getColumn(0).setResizable(false);
            Tb_SanPham.getColumnModel().getColumn(0).setPreferredWidth(100);
            Tb_SanPham.getColumnModel().getColumn(1).setResizable(false);
            Tb_SanPham.getColumnModel().getColumn(1).setPreferredWidth(100);
            Tb_SanPham.getColumnModel().getColumn(2).setResizable(false);
            Tb_SanPham.getColumnModel().getColumn(2).setPreferredWidth(120);
            Tb_SanPham.getColumnModel().getColumn(3).setResizable(false);
            Tb_SanPham.getColumnModel().getColumn(3).setPreferredWidth(100);
            Tb_SanPham.getColumnModel().getColumn(4).setResizable(false);
            Tb_SanPham.getColumnModel().getColumn(4).setPreferredWidth(100);
            Tb_SanPham.getColumnModel().getColumn(5).setResizable(false);
            Tb_SanPham.getColumnModel().getColumn(5).setPreferredWidth(100);
            Tb_SanPham.getColumnModel().getColumn(6).setResizable(false);
            Tb_SanPham.getColumnModel().getColumn(6).setPreferredWidth(80);
            Tb_SanPham.getColumnModel().getColumn(7).setResizable(false);
            Tb_SanPham.getColumnModel().getColumn(7).setPreferredWidth(80);
            Tb_SanPham.getColumnModel().getColumn(8).setResizable(false);
            Tb_SanPham.getColumnModel().getColumn(8).setPreferredWidth(80);
        }

        SanPham_btn_Tim.setText("Tìm");
        SanPham_btn_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanPham_btn_TimActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(SanPham_txt_Tim);

        jButton2.setText("Lọc");
        jButton2.setToolTipText("");

        SanPham_btn_TaiLai.setText("Tải lại");
        SanPham_btn_TaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanPham_btn_TaiLaiActionPerformed(evt);
            }
        });

        SanPham_btn_Them.setBackground(new java.awt.Color(51, 153, 255));
        SanPham_btn_Them.setText("Thêm sản phẩm");
        SanPham_btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanPham_btn_ThemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý sản phẩm");

        jPanel1.setBackground(new java.awt.Color(229, 231, 235));

        Tb_SanPham1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên sản phẩm", "Loại", "Ảnh", "Số lượng", "Giá vốn", "Giá lời"
            }
        ));
        jScrollPane4.setViewportView(Tb_SanPham1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 514, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SanPham_btn_Tim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SanPham_btn_TaiLai))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SanPham_btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SanPham_btn_Tim)
                            .addComponent(SanPham_btn_TaiLai))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(SanPham_btn_Them)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SanPham_btn_TaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanPham_btn_TaiLaiActionPerformed
        sanPhamBUS.hienThiSanPhamLenTable(Tb_SanPham);
        SanPham_txt_Tim.setText("");
    }//GEN-LAST:event_SanPham_btn_TaiLaiActionPerformed

    private void SanPham_btn_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanPham_btn_TimActionPerformed
        String tuKhoa = SanPham_txt_Tim.getText().trim();
        sanPhamBUS.HienThiSanPhamTimKiem(Tb_SanPham, tuKhoa);
    }//GEN-LAST:event_SanPham_btn_TimActionPerformed

    private void SanPham_btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanPham_btn_ThemActionPerformed
        SanPham_Them_Dialog t = new SanPham_Them_Dialog(null, true, sanPhamBUS, Tb_SanPham);
        t.setLocationRelativeTo(null);
        t.setVisible(true);
    }//GEN-LAST:event_SanPham_btn_ThemActionPerformed

    private void SanPham_pop_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanPham_pop_SuaActionPerformed
        int selectedRow = Tb_SanPham.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm để sửa!",
                    "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) Tb_SanPham.getModel();
        SanPham sanPham = new SanPham();
        sanPham.setMaSanPham((Integer) model.getValueAt(selectedRow, 0));
        sanPham.setTenLoaiSanPham((String) model.getValueAt(selectedRow, 1));
        sanPham.setAnhSanPhamURL((String) model.getValueAt(selectedRow, 2));
        sanPham.setTenSanPham((String) model.getValueAt(selectedRow, 3));
        sanPham.setNhaSanXuat((String) model.getValueAt(selectedRow, 4));
        sanPham.setTrangThai(((String) model.getValueAt(selectedRow, 5)).equals("Hoạt động"));
        sanPham.setSoLuong((Integer) model.getValueAt(selectedRow, 6));
        sanPham.setGiaVon((Double) model.getValueAt(selectedRow, 7));
        sanPham.setGiaLoi((Double) model.getValueAt(selectedRow, 8));

        SanPham_Sua_Dialog suaDialog = new SanPham_Sua_Dialog(null, true, sanPhamBUS, Tb_SanPham, sanPham);
        suaDialog.setLocationRelativeTo(null);
        suaDialog.setVisible(true);
    }//GEN-LAST:event_SanPham_pop_SuaActionPerformed

    private void SanPham_pop_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanPham_pop_XoaActionPerformed
        int selectedRow = Tb_SanPham.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm để xóa!",
                    "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy mã sản phẩm từ dòng được chọn
        DefaultTableModel model = (DefaultTableModel) Tb_SanPham.getModel();
        int maSanPham = (Integer) model.getValueAt(selectedRow, 0);

        // Xác nhận xóa
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xóa sản phẩm với mã " + maSanPham + " không?",
                "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (sanPhamBUS.xoaSanPham(maSanPham)) {
                JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                sanPhamBUS.hienThiSanPhamLenTable(Tb_SanPham); // Tải lại bảng
            } else {
                JOptionPane.showMessageDialog(this, "Xóa sản phẩm thất bại!",
                        "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_SanPham_pop_XoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SanPham_btn_TaiLai;
    private javax.swing.JButton SanPham_btn_Them;
    private javax.swing.JButton SanPham_btn_Tim;
    private javax.swing.JMenuItem SanPham_pop_Sua;
    private javax.swing.JMenuItem SanPham_pop_Xoa;
    private javax.swing.JPopupMenu SanPham_pop_editdel;
    private javax.swing.JTextPane SanPham_txt_Tim;
    private javax.swing.JTable Tb_SanPham;
    private javax.swing.JTable Tb_SanPham1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
